### ISSUE TITLE
Sorting issue with automated table extensions

### ISSUE THREAD

**Issue by bgyori** [biomappings/biomappings#51]
The build here 
https://github.com/biomappings/biomappings/runs/3157071733?check_suite_focus=true
complains about the sort order:
```
======================================================================
FAIL: Test the true curated mappings are in a canonical order.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/biomappings/biomappings/.tox/py/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/runner/work/biomappings/biomappings/src/biomappings/tests/test_validity.py", line 51, in test_curations_sorted
    ), "True curations are not sorted"
AssertionError: True curations are not sorted

======================================================================
FAIL: Test the false curated mappings are in a canonical order.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/biomappings/biomappings/.tox/py/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/runner/work/biomappings/biomappings/src/biomappings/tests/test_validity.py", line 58, in test_false_mappings_sorted
    ), "False curations are not sorted"
AssertionError: False curations are not sorted

======================================================================
FAIL: Test the unsure mappings are in a canonical order.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/biomappings/biomappings/.tox/py/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/runner/work/biomappings/biomappings/src/biomappings/tests/test_validity.py", line 65, in test_unsure_sorted
    ), "Unsure curations are not sorted"
AssertionError: Unsure curations are not sorted

----------------------------------------------------------------------
Ran 6 tests in 1.103s
```

**Comment by cthoyt** [comment]
Quick fix is to run `biomappings lint` but the real issue is the web interface should make updates that maintain the sort order
